routingRules:
  - version: "2.0.0"
    targetType: "bpp"
    endpoints:
      - confirm
      - status

  - version: "2.0.0"
    targetType: "url"
    target:
      url: "https://discovr-beckn.krishiupai.com/beckn"
    endpoints:
      - discover
