routingRules:
  - version: "2.0.0"
    targetType: "bpp"
    endpoints:
      - on_status
      - on_confirm
  
  - version: "2.0.0"
    targetType: "url"
    target:
      url: "https://fabric.nfh.global/beckn/catalog"
    endpoints:
      - publish